### ISSUE TITLE
Implement Search

### ISSUE THREAD

**Issue by humphd** [Seneca-ICTOER/IPC144#10]
Docusaurus has a really cool [search](https://docusaurus.io/docs/search) feature, which can be integrated with the site.  We'd like to add search, so it would be great if someone can pick this up.

**Comment by ycechungAI** [comment]
Im assuming you do not apply the usual method of implementing Algolia DocSearch​ by signing up at https://docsearch.algolia.com/apply/ then just enabling it

**Comment by ycechungAI** [comment]
And do i run my own DocSearch crawler as suggested on the docusaurus website?

**Comment by ycechungAI** [comment]
what do u want index_name to be? for now i have it as docusaurus.

**Comment by humphd** [comment]
Sounds reasonable

**Comment by ycechungAI** [comment]
The general settings I commited is standard.
Things to note is you need to create an index named "docusaurus".
You need the main api_key to have ACLs search, addObject, deleteObject, editSearch - is this the .env or config.json file
![image](https://user-images.githubusercontent.com/55400510/141247456-8837f005-ef43-4a4f-9539-0b1828fa5d44.png)
You need a secondary api_key to do the searching with ACLs search - this is usually placed in docusaurus.config.js
Need to expand on this by creating a CI with the template I found [docsearch-action-link](https://github.com/marketplace/actions/algolia-docsearch-action) - used for future reference

**Comment by humphd** [comment]
Closing in favour of #125
