### ISSUE TITLE
Fix Broken Links

### ISSUE THREAD

**Issue by humphd** [Seneca-ICTOER/IPC144#106]
When we run `yarn build` on `main`, it errors with lots of broken links:

```
✔ Service Worker
  Compiled successfully in 988.46ms

Unable to build website for locale "en".
Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /computations/testing-and-debugging:
   -> linking to /A-Introduction/computers#central-processing-unit (resolved as: /A-Introduction/computers)
   -> linking to /A-Introduction/computers#primary-memory (resolved as: /A-Introduction/computers)

- On source page path = /data-structures/arrays:
   -> linking to /C-Data-Structures/structures

- On source page path = /data-structures/structures:
   -> linking to /C-Data-Structures/arrays
   -> linking to /D-Modularity/pointers#addresses (resolved as: /D-Modularity/pointers)
   -> linking to /C-Data-Structures/arrays#parallel-arrays (resolved as: /C-Data-Structures/arrays)
   -> linking to /B-Computations/testing-and-debugging#walkthrough-table (resolved as: /B-Computations/testing-and-debugging)

- On source page path = /introduction/compilers:
   -> linking to /B-Computations/style-guidelines#comments (resolved as: /B-Computations/style-guidelines)

- On source page path = /introduction/computers:
   -> linking to /F-Refinements/algorithms

- On source page path = /modularity/pointers:
   -> linking to /F-Refinements/more-input-and-output#conversion-specifiers (resolved as: /F-Refinements/more-input-and-output)

- On source page path = /refinements/algorithms:
   -> linking to /C-Data-Structures/arrays#parallel-arrays (resolved as: /C-Data-Structures/arrays)

- On source page path = /refinements/more-input-and-output:
   -> linking to /F-Refinements/algorithms
   -> linking to /A-Introduction/compilers#the-c-compiler (resolved as: /A-Introduction/compilers)
   -> linking to /B-Computations/testing-and-debugging#debugging-techniques (resolved as: /B-Computations/testing-and-debugging)

- On source page path = /refinements/string-library:
   -> linking to /A-Introduction/compilers#the-c-compiler (resolved as: /A-Introduction/compilers)

    at reportMessage (/Users/humphd/repos/IPC144/node_modules/@docusaurus/utils/lib/index.js:308:19)
    at handleBrokenLinks (/Users/humphd/repos/IPC144/node_modules/@docusaurus/core/lib/server/brokenLinks.js:142:35)
    at async buildLocale (/Users/humphd/repos/IPC144/node_modules/@docusaurus/core/lib/commands/build.js:163:5)
    at async tryToBuildLocale (/Users/humphd/repos/IPC144/node_modules/@docusaurus/core/lib/commands/build.js:35:20)
    at async mapAsyncSequencial (/Users/humphd/repos/IPC144/node_modules/@docusaurus/utils/lib/index.js:263:24)
    at async build (/Users/humphd/repos/IPC144/node_modules/@docusaurus/core/lib/commands/build.js:71:25)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by humphd** [comment]
It looks like a lot of these are due to the `#anchor` addition on the end.  I bet Docusaurus is having issues with it.  I also notice:

> Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

@CameronGray1210 should we disable the broken link check so it will pass?

**Comment by Kevan-Y** [comment]
@humphd Probably, the `slug` option is some md files, that causing this issue.

https://github.com/Seneca-ICTOER/IPC144/blob/1941712a5dce6a23011cd4440b10872630221fa1/docs/A-Introduction/computers.md?plain=1#L25

https://github.com/Seneca-ICTOER/IPC144/blob/1941712a5dce6a23011cd4440b10872630221fa1/docs/F-Refinements/algorithms.md?plain=1#L5

The link should be `/refinements/algorithms` instead of `/F-Refinements/algorithms`

**Comment by humphd** [comment]
Interesting.  What about `-> linking to /A-Introduction/computers#central-processing-unit (resolved as: /A-Introduction/computers)`, isn't that the extra anchor?

**Comment by Kevan-Y** [comment]
> Interesting. What about `-> linking to /A-Introduction/computers#central-processing-unit (resolved as: /A-Introduction/computers)`, isn't that the extra anchor?

https://github.com/Seneca-ICTOER/IPC144/blob/1941712a5dce6a23011cd4440b10872630221fa1/docs/B-Computations/testing-and-debugging.md?plain=1#L21

Changed ` [CPU](/A-Introduction/computers#central-processing-unit "Central Processing Unit")` to `[CPU](/introduction/computers#central-processing-unit "Central Processing Unit")`

**Comment by Kevan-Y** [comment]
We should decide to use `slug` to rename the path or use the folder as path name.

**Comment by Kevan-Y** [comment]
I can work on this issue if no one wants it.

**Comment by humphd** [comment]
@Kevan-Y that would be amazing, thank you.

**Comment by Kevan-Y** [comment]
@humphd 
Solution 1:
Should we add `slug` for every .md file and relink every link.

```
├───A-Introduction
│       compilers.md
│       computers.md
│       information.md
│
├───B-Computations
│       a-simple-calculation.md
```

compilers will be `/Introduction/compilers ` instead of  `/A-Introduction/compilers `.
a-simple-calculation will be `/Computations/a-simple-calculation` instead of  `/B-Computations/a-simple-calculation`

Solution 2: remove slug on every .md file, it should fix that too.

Why do we need to add `slug`?

**Comment by humphd** [comment]
We need @CameronGray1210 to weigh in on this.  The value of a slug is that it makes a URL pretty, and easier to share (if done well).  We can achieve something similar by using "pretty" directory/file names.  Either works.

**Comment by humphd** [comment]
#117 is a bandaid fix for this

**Comment by Kevan-Y** [comment]
Any update? @CameronGray1210

**Comment by CameronGray1210** [comment]
Let's remove the "slugs" and go with file paths for linking.
