### ISSUE TITLE
Run yarn build, prettier-check on every PR in GitHub Actions

### ISSUE THREAD

**Issue by humphd** [Seneca-ICTOER/IPC144#107]
In #106 we ran into an issue where we have broken links which means we can't complete a build.  Let's add a `yarn build` step to our pull request CI workflow, such that every PR gets fully built, and if it fails we can spot it immediately.

**Comment by humphd** [comment]
In #117 we're turning this from a fatal error to a warning.  Once this is done, let's go back to having it be an error so that we can catch it in CI.

**Comment by humphd** [comment]
Let's also include `prettier-check` so we catch people forgetting to run `prettier` on their changes, now that #50 has been merged.

**Comment by mqnguyen5** [comment]
@humphd I can work on this one.

**Comment by humphd** [comment]
@mqnguyen5 absolutely, go for it.  Thank you!
