### ISSUE TITLE
Improve layout of ASCII Table

### ISSUE THREAD

**Issue by humphd** [Seneca-ICTOER/IPC144#111]
In #80 we converted the ASCII Table from an image to text.  We'd like to do another improvement to the layout: put the Capital and lowercase ASCII letters across from each other, so it's easier to scan through and find both.  Here's an example of what we mean:

https://upload.wikimedia.org/wikipedia/commons/1/1b/ASCII-Table-wide.svg

Notice how A and a are beside each other:

<img width="388" alt="Screen Shot 2021-11-19 at 11 22 29 AM" src="https://user-images.githubusercontent.com/427398/142656587-e6863f39-bcdb-4314-b56b-4c84944cdd04.png">

**Comment by joshuali7536** [comment]
Hi I would like to help fix this issue.

**Comment by humphd** [comment]
Assigned
