### ISSUE TITLE
Figure out highlighting colour(s) and strategy for light and dark mode

### ISSUE THREAD

**Issue by humphd** [Seneca-ICTOER/IPC144#112]
We have places were we want to highlight something (e.g., cells in a table) by using a background colour.  For example, the cells in this table on the right:

![](https://user-images.githubusercontent.com/52294825/142270767-6bc5bcad-a43a-4b66-bee3-ca044f0eea2d.png)

When we switch to dark mode, this doesn't work well.  We need to find a colour, or two colours, that can be used for this, and apply it based on some CSS class or variable.  Docusaurus likely already has a way, see https://docusaurus.io/docs/styling-layout, etc.

**Comment by lyu4321** [comment]
Hi @humphd, could I work on this?

**Comment by humphd** [comment]
Absolutely, go for it.
