### ISSUE TITLE
Bring all images from ict.senecacollege.ca into the repo

### ISSUE THREAD

**Issue by humphd** [Seneca-ICTOER/IPC144#113]
See https://github.com/Seneca-ICTOER/IPC144/search?q=https%3A%2F%2Fict.senecacollege.ca%2F for instances where we're still linking to (images) on the old IPC144 site.  These should all be changed to bring the images into this repo and linked to locally.

**Comment by Kevan-Y** [comment]
Can I work on this issue?

**Comment by humphd** [comment]
@Kevan-Y that would be great
