### ISSUE TITLE
Investigate using the ideal image plugin

### ISSUE THREAD

**Issue by humphd** [Seneca-ICTOER/IPC144#12]
Docusaurus has a cool plugin you can use for generating [ideal image sizes/formats](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-ideal-image) when doing a production build.  We could use it to create responsive images for various screen sizes.

At this point, a lot of our images are small, but it would be interesting to experiment with this feature in a few places, and learn how it works.  We could progressively add more of it as we replace images, and use higher resolution images that this plugin will scale for different use cases.

**Comment by aserputov** [comment]
Hey, I would like to work on this issue. Could you please assign me?

**Comment by humphd** [comment]
@aserputov done
