### ISSUE TITLE
Use /img vs. static/img for all image URLs

### ISSUE THREAD

**Issue by humphd** [Seneca-ICTOER/IPC144#126]
We have a [few places](https://github.com/Seneca-ICTOER/IPC144/search?q=static%2Fimg) where we include the `static/` dir in our image URLs.  We don't need this.  They can all be `/img/*`.

@Kevan-Y do you have interest in this, since you're working on the other image import?

**Comment by Kevan-Y** [comment]
I can work on it too, I can fix it in my other PR
