### ISSUE TITLE
Centre all Markdown Tables

### ISSUE THREAD

**Issue by humphd** [Seneca-ICTOER/IPC144#127]
We'd like to find a solution so that we can automatically (e.g., through CSS) centre all tables in Markdown.  Doing so might mean we have to wrap all `<table>` elements in a `<div>` and set its alignment.  But there might be an easier way.

**Comment by joshuali7536** [comment]
Hi, can I also work on this one too?

**Comment by humphd** [comment]
Yes, assigned.

**Comment by joshuali7536** [comment]
@humphd How would I go about wrapping all `<table>` elements globally with a `<div>`?

**Comment by humphd** [comment]
You'd have to do it manually.  But I think you can do this with CSS on the `table` elements.  Here's my quick test with dev tools:

<img width="1039" alt="Screen Shot 2021-12-08 at 9 51 58 AM" src="https://user-images.githubusercontent.com/427398/145229513-7eb15812-e980-4463-8bb0-e3c83de42c3d.png">

```css
margin-left: auto;
margin-right: auto;
width: fit-content;
```

This could be turned into a class we apply to tables maybe, or could be done globally to all tables?  Not sure.

**Comment by joshuali7536** [comment]
Oh yes that works, I was originally working with the `<table>` elements directly but was having trouble because `margin-left: auto` and `margin-right: auto` weren't doing anything. I did not realize I needed to have `width: fit-content` as well.
