### ISSUE TITLE
Use React style naming for HTML attributes (className, colSpan)

### ISSUE THREAD

**Issue by Kevan-Y** [Seneca-ICTOER/IPC144#129]
**Desctiption**
When running in the development mode.
There is some console error in some pages.
For example:
![image](https://user-images.githubusercontent.com/58233223/143604507-93c694c0-03ef-4bd9-a224-e761954ff837.png)
![image](https://user-images.githubusercontent.com/58233223/143604536-dd951b37-0954-4514-8a58-a9159cbf5cd9.png)

Check all the pages and fix those issues.

**Comment by humphd** [comment]
See https://github.com/Seneca-ICTOER/IPC144/search?q=colspan

In HTML, `colspan` is correct.  But in MDX (Markdown with React), we need to use `colSpan`

**Comment by Kevan-Y** [comment]
https://github.com/Seneca-ICTOER/IPC144/search?q=class

Also for `class`, it should be `className`.

**Comment by Kevan-Y** [comment]
Will work on this issue.
