### ISSUE TITLE
Create GitHub Actions Workflow for Deployment

### ISSUE THREAD

**Issue by humphd** [Seneca-ICTOER/IPC144#13]
We'd like to have the production site get updated automatically on every `push`/`merge` to the `main` branch.  It would be ideal if we could do this automatically using GitHub Actions.  [Docusaurus has docs for this](https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions) that someone should research and implement.  You can test it out in your own fork and make sure it works before we merge it here.

**Comment by trangntt-016** [comment]
Hi @humphd ,

I have never done Github Actions Workflow before. I'm interested in trying it!

**Comment by humphd** [comment]
@trangntt-016 I love your attitude and willingness to try something new, well done!  Absolutely, you can take this issue.  NOTE: we're going to be working with GitHub Actions soon in our open source course as well.

**Comment by trangntt-016** [comment]
> @trangntt-016 I love your attitude and willingness to try something new, well done! Absolutely, you can take this issue. NOTE: we're going to be working with GitHub Actions soon in our open source course as well.

thanks @humphd <3
