### ISSUE TITLE
React errors/warnings on page load

### ISSUE THREAD

**Issue by nguyenhung15913** [Seneca-ICTOER/IPC144#133]
After running <code>yarn install</code> and <code>yarn start</code>, <code>localhost:3000</code> ran in the browser but the site was empty.
Below is the console with errors:
![image](https://user-images.githubusercontent.com/69558780/144151245-b352c118-526c-4bae-bc97-08552f0898c0.png)

**Comment by dbelokon** [comment]
I would like to work on this 😄 Can I get more details about the configuration? How would I reproduce this bug?

**Comment by humphd** [comment]
@nguyenhung15913 has given steps to reproduce in the first comment, namely:

- pull `main` so you're up to date
- `yarn` to install dependencies
- `yarn start`
- browser to `localhost:3000`
- confirm the errors in the console

**Comment by nguyenhung15913** [comment]
Somehow the site is working successfully after I restarted my laptop.

**Comment by HyperTHD** [comment]
Just for future reference, unless you're making a hook function, hooks like `useState` and `useEffect` always belong inside the component function being created at the top level and no where else.

**Comment by dbelokon** [comment]
> Somehow the site is working successfully after I restarted my laptop. @dbelokon @humphd

Yeah, I can confirm. As per my screenshot, no errors are shown:

![image](https://user-images.githubusercontent.com/67607236/144358853-bb65db50-e8fb-4722-9650-1c40214ff54a.png)

Maybe there was no error at all?

**Comment by humphd** [comment]
OK, great news.  Thanks for testing, everyone.
