### ISSUE TITLE
Add 3 pages to Navigation Bar

### ISSUE THREAD

**Issue by kiennguyenchi** [Seneca-ICTOER/IPC144#138]
I would like to add 3 more pages to the navigation bar.

- [ ] 1/ Course Outline: 
* When student clicks on Course Outline on navigation bar, it will direct student to [IPC144 Course Outline](https://www.senecacollege.ca/ssos/findwithoutsemester/ipc144/sict)
- [ ] 2/ Workshops: 
* I would like to create a *Workshops page*. 
* When student clicks on **Workshops** on navigation bar, a *Workshops page* will show a list of workshops that students need to complete and their hyperlinks to workshops in [IPC Workshops Repo](https://github.com/Seneca-144100/IPC-Workshops)
- [ ] 3/ Milestones: 
* I would like to create a *Milestones page*. 
* When student clicks on **Milestones** on navigation bar, a *Milestones page* will show a list of milestones that students need to complete and their hyperlinks to workshops in [IPC Milestones Repo](https://github.com/Seneca-144100/IPC-Project)

**Comment by CameronGray1210** [comment]
@kiennguyenchi : Thanks for the idea's, however one our primary directives in doing this open source course notes is to decouple the integration of workshops and projects.  Workshop and project links are provided to students using other less public methods (LMS/Blackboard).  The course outline as well is something that is made available via the LMS (Blackboard) and should not be part of the course notes.  We want the course notes to be completely independent from any course specific material.
