### ISSUE TITLE
PDF Export of full text

### ISSUE THREAD

**Issue by humphd** [Seneca-ICTOER/IPC144#14]
One thing we'd like to support is a PDF export of the entire text.  It looks like there isn't an official way to do this, but there are some community attempts:

* https://github.com/kohheepeace/mr-pdf
* https://github.com/signcl/docusaurus-prince-pdf 

Let's experiment and see how well we can make this work.

**Comment by TueNguyen2911** [comment]
Hi, can I try tackling this?

**Comment by humphd** [comment]
Yes, absolutely, go for it.

**Comment by TueNguyen2911** [comment]
I'm trying to find our Docusaurus version but couldn't. Are we using Docusaurus v2 or v1?

**Comment by humphd** [comment]
v2, see https://github.com/Seneca-ICTOER/IPC144/blob/main/package.json#L18

**Comment by TueNguyen2911** [comment]
> v2, see https://github.com/Seneca-ICTOER/IPC144/blob/main/package.json#L18

Thank you, I got it when I ran it

**Comment by TueNguyen2911** [comment]
After trying a few tools, I find that [mr-pdf](https://github.com/kohheepeace/mr-pdf) works well with Docusaurus v2 and it comes with multiple options. 

This is the command line script I use:
```bash 
npx mr-pdf --initialDocURLs="http://localhost:3000" --contentSelector="article" --paginationSelector=".pagination-nav__item--next > a" --excludeSelectors=".margin-vert--xl a" --coverImage="https://download.logo.wine/logo/Seneca_College/Seneca_College-Logo.wine.png" --coverTitle="Seneca-IPC144"
```
I'm thinking of saving this entire script in the `scripts` property but it will be very long. I'm not sure if there's a better way to save the script.

You can take a look at the [pdf](https://drive.google.com/drive/u/0/my-drive)

**Comment by humphd** [comment]
I would add `mr-pdf` as a `devDependency`, and then make a file called `convert-to-pdf.js` which is a node script calls `mr-pdf`

Or, you can write a shell script (`convert-to-pdf.sh` and `convert-to-pdf.bat`) that does your command line above with `npx`.  This is how VSCode does its scripts for cross-platform compatibility, see https://github.com/microsoft/vscode/tree/main/scripts.

The PDF you link doesn't point to anything, it just drops me into my Google Drive.  Can you drag-and-drop it into this issue and post it here?

**Comment by TueNguyen2911** [comment]
Hi, here is the pdf [Seneca-IPC144.pdf](https://github.com/Seneca-ICTOER/IPC144/files/7491349/Seneca-IPC144.pdf)
