### ISSUE TITLE
Increase Table of Contents depth 

### ISSUE THREAD

**Issue by humphd** [Seneca-ICTOER/IPC144#16]
It's possible to configure the min/max depth of the table of contents (e.g., how many heading levels to show), see https://docusaurus.io/docs/api/themes/configuration#table-of-contents.  We use up to 4 levels (i.e., `h4` or `####`) but the final level isn't being displayed.  Let's fix this.  An example page is `docs/B-Computations/logic.md`.

**Comment by menghif** [comment]
I would like to take this one.

**Comment by humphd** [comment]
All you @menghif, go for it.
