### ISSUE TITLE
Add Prettier as source code formatter

### ISSUE THREAD

**Issue by Kevan-Y** [Seneca-ICTOER/IPC144#24]
Adding [Prettier](https://prettier.io/docs/en/install.html) will allow us to have a general styling for every contributor that works on this  project.

**Comment by humphd** [comment]
Let's include a `.vscode/` directory with settings and plugin recommendations, and also add a Husky-based git pre-commit hook so this always gets run.

**Comment by mqnguyen5** [comment]
I'm willing to give this one a shot. Can you give me more details on what should be added?

**Comment by humphd** [comment]
@mqnguyen5 I would look at how [Docusaurus uses Prettier on GitHub](https://github.com/facebook/docusaurus) and use that as a guide.

This is very similar to your lab.  We need:

- add prettier to dependencies
- prettier config file
- prettier ignore file to skip anything we don't want touched
- changes to the npm scripts to include prettier
- git hook with Husky to run prettier on every commit
- add a .vscode/ directory and include the prettier extension in the list of suggestions
- run prettier over the entire code base so it gets formatted

One thing we might run into and need to be aware of: how will it affect the code snippets in the Markdown files?  Will it break anything that the profs teaching IPC144 need?  We'll have to test and see.

**Comment by mqnguyen5** [comment]
Aside from that, is there a specific sets of formatting rules that I should include in the `.prettierrc`?

**Comment by humphd** [comment]
Use what we have in Telescope
