### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by menghif** [Seneca-ICTOER/IPC144#25]
All markdown files are in [docs](https://github.com/Seneca-ICTOER/IPC144/tree/main/docs). The links in the [README](https://github.com/Seneca-ICTOER/IPC144/blob/main/README.md) should be fixed to reflect that.

**Comment by humphd** [comment]
Nice catch.

**Comment by Kevan-Y** [comment]
Anyone working on this? If not Can work on it?

**Comment by humphd** [comment]
Go for it, @Kevan-Y.
