### ISSUE TITLE
Find better resolution icon

### ISSUE THREAD

**Issue by Kevan-Y** [Seneca-ICTOER/IPC144#32]
Follow up of #11

Our current PWA icons in (.static/img/pwa) using a low resolution and blurry icon. We want to replace that to a higher resolution.

**Comment by gusmccallum** [comment]
Hi I'd like to work on this, please assign it to me.

**Comment by humphd** [comment]
Awesome, thanks @gusmccallum.  Assigned.

**Comment by humphd** [comment]
Fixed by https://github.com/Seneca-ICTOER/IPC144/pull/53. @gusmccallum when you do a PR to fix an issue, use the text "Fixes #..." in the description so GitHub autocloses it when we merge.
