### ISSUE TITLE
Audit & fix Information.md page 

### ISSUE THREAD

**Issue by Yoda-Canada** [Seneca-ICTOER/IPC144#44]
This is a sub-issue of #18.
I'd like to audit and fix the Information.md page based on tasks listed below.

## Check List
- [x] Look for any typos
- [x] Make sure all Markdown is correctly done. The conversion was done automatically by a tool, so there may be more idiomatic ways to do some things
- [x] Check the page in a Desktop browser. Does it look OK? Are there any issues that need to be fixed?
- [x] Check the page in a Mobile browser. Does it look OK? Are there any issues that need to be fixed?
- [x] Try the page in both Light and Dark mode. Are there any issues that need to be fixed?
- [x] Try running the page through Lighthouse: https://developers.google.com/web/tools/lighthouse. Are there any issues that need to be fixed?
- [x] Try running the page through Web Hint: https://webhint.io/. Are there any issues that need to be fixed?
- [x] Tables that are really wide (types.md) could be converted to use SVG or flex/grid. Make wide visual tables fit in the available viewport. Another example is the table in docs/D-Modularity/pointers.md, where we should reduce the vertical padding/margins on tables. The tables are too large, and probably shouldn't be tables at all.
- [x] Prefer Markdown tables vs. raw HTML tags
- [x] Fix colours in tables so it uses global styles vs. inline styles
- [x] Use alt tags for all images. See https://supercooldesign.co.uk/blog/how-to-write-good-alt-text for suggestions
- [x] Avoid blockquote for indentation, and prefer q or blockquote only when actually quoting. Use Admonitions instead. Example: docs/D-Modulatirty/pointers.md: there are places where > Blockquote are being used and Admonitions could replace it. “Note:” Lightbulb info Admonition.
- [x] Make sure images work in dark and light modes. For example, docs/8-Computations/logic.md Flags image is white background, needs to work in dark. Create a “negative” or SVG so we can do Dark Mode? Can we programmatically create this negative?
- [x] Change colours for tables (don’t use Yellow). We should use the default colour theme.
- [x] Avoid using &lt;b&gt; and &lt;i&gt; to do emphasis.
- [x] Use backticks and all code for memory addresses and such in tables that use things like void, int, function names, memory addresses.
- [x] Make sure all code blocks use syntax highlighting
- [x] Centre images horizontally (esp. when they are small) so they work well at all responsive sizes
- [x] Check sub-script and super-script that they are correctly used in all cases
- [x] Consider including inter-site links to other pages that have related info
- [x] All links should have descriptive text for accessibility
- [x] Make sure that sub-headings (right-hand side) for each document are correct.
- [x] Improve readability of code comments (i.e., // and /*...*/) in dark mode (even light mode might need some work)
- [x] In places where ***...*** was used as a fourth heading level, use #### instead.
- [x] Fix Frontmatter for page to include proper id, title, slug, etc.

**Comment by Yoda-Canada** [comment]
When the web page changed to dark model, the downward arrows and the letter in the bottom right corner are not clear. I save the image in the img folder and link it to the information page. The issue fixed.![3f69ac9f38ed3d2cb15f490eedd3e0d](https://user-images.githubusercontent.com/55161917/141400730-03425a18-79d3-45b3-978f-4bcb1fd39e22.png)

**Comment by Yoda-Canada** [comment]
The "https://github.com/Seneca-ICTOER/IPC144/blob/main/docs/A-Introduction/information.md" cannot display images. I change the path from  "/img/bytenibbit.jpg" to  "../../static/img/bytenibbit.jpg".    
![1636946432](https://user-images.githubusercontent.com/55161917/141717181-2e2516c4-be86-4457-ab6a-269c6642ebff.png)

**Comment by Yoda-Canada** [comment]
@humphd Do you mind I close PR#81 and create a new PR? I have modified all issues according to classmates' reviews, but there are lots of commits. There is a big problem and I can't squash them to one commit. The branches are becoming more and more complex. I feel I can't repair them

**Comment by humphd** [comment]
Alright.  NOTE: you need to not `pull` into your branch.  When you `pull` it does a `fetch` and a `merge`.  You should be on the `main` branch only when you `pull`.  Please figure out the workflow before you begin on it again.

**Comment by Yoda-Canada** [comment]
close this issue since PR 119
