### ISSUE TITLE
Docusaurus Plugin to add PWA support.

### ISSUE THREAD

**Issue by aserputov** [Seneca-ICTOER/IPC144#47]
While working on issue #12, I found that maybe it would be great to access the IPC144 resources on desktop&offline.
[This plugin](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-pwa) generates a Service Worker in production build only and allows you to create a fully PWA-compliant documentation site with offline and installation support.

Waiting for your opinions, here⤵️

**Comment by humphd** [comment]
@aserputov yeah, it's awesome and @Kevan-Y has already added it and got it merged on `main` in #22.
