### ISSUE TITLE
Standardize frontmatter across all pages

### ISSUE THREAD

**Issue by humphd** [Seneca-ICTOER/IPC144#64]
In https://github.com/Seneca-ICTOER/IPC144/pull/61/files#diff-e9bdd80935a7058d016ee32cb30d64969fd2d18cc9324d64a33b0557b18b12c9 and https://github.com/Seneca-ICTOER/IPC144/pull/60/files#diff-be05c13053f9c29afd50066de996d568f9913764c46318677fd945bd9a5c008dR2 we're starting to see a standard emerge for Markdown frontmatter.  For example:

```md
---
id: pointers
title: Pointers
sidebar_position: 2
slug: /modularity/pointers
description: A variable that holds an address is called a pointer.
---
```

The full list of properties we can define is at https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#markdown-frontmatter.

Let's come up with a standard to use, and then roll it out across all the pages.  We can come back to this after the first round of audits for #18 comes in.

**Comment by CameronGray1210** [comment]
Decided NOT to use SLUG's in frontmatter.

**Comment by MizuhoOkimoto** [comment]
Hi, I would like to work on it. Thank you!

**Comment by humphd** [comment]
#102, #140, #141, will need careful review/help from you so that they use your new standard.

**Comment by MizuhoOkimoto** [comment]
I have a question about code blocks in the .md files. When people worked on #18 , some people deleted extra indentations, and others didn't. Which code format would you prefer?

For example, 
- Keep indentations: #94  
<img src="https://user-images.githubusercontent.com/54873998/144683575-b7d7df84-cc9f-44da-a4d4-2721d97ec427.png" width="430">

- Delete indentations: #88 
<img src="https://user-images.githubusercontent.com/54873998/144683477-7d37d319-06be-44d9-93f5-207590f55d73.png" width="430">

**Comment by humphd** [comment]
I think Prettier will standardize it to 2-spaces.  Some files probably need to have prettier run on them (in PRs).

**Comment by MizuhoOkimoto** [comment]
Okay, I will do the reviews in PRs and also check other files and make them standardized. Thank you, @humphd !
