### ISSUE TITLE
Convert ASCII Collating Sequence to text/table

### ISSUE THREAD

**Issue by humphd** [Seneca-ICTOER/IPC144#66]
Currently we are using an image for the ASCII Collating Sequence, see https://cghub.ca/Resources-Appendices/ascii-collating-sequence.  This isn't accessible, and should be converted into text and a Markdown table.

**Comment by aserputov** [comment]
@humphd, could you please assign me to this issue? I would like to convert picture into table and see how to combine it with #46

**Comment by humphd** [comment]
done
