### ISSUE TITLE
Update Dependencies to run algolia-scraper.yml 

### ISSUE THREAD

**Issue by ycechungAI** [Seneca-ICTOER/IPC144#69]
Make the proper dependencies and builds on CI, enabling user groups for docker? 
ie. You need python 3.6.15 or newer with pyenv installed.
Refer to the following
[https://docsearch.algolia.com/docs/legacy/run-your-own](run-your-own)

## Setup

You need to go through the steps of signup up for an account etc listed on  CONTRIBUTION.md for Search section.
Refer to #10 for information on environment variables and secrets
[https://github.com/marketplace/actions/algolia-docsearch-action](algolia-docsearch-action)

**Comment by CameronGray1210** [comment]
Will be using other search options.
